# Generated by Django 4.1.4 on 2022-12-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_product_thumnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
