# Generated by Django 4.1.4 on 2022-12-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
    ]
